#!/bin/bash

echo; echo -------- Installing Additional Tools --------; echo;
apt -y install openssh-server nano cron net-tools expect # ssh, nano, cron, ifconfig (and friends), expect (for scripted interaction)
/etc/init.d/ssh start

echo; echo -------- Installing Apache and Mod_WSGI --------; echo;
apt -y install apache2 libapache2-mod-wsgi-py3
# setup apache to use wsgi and connect to django
sed -i.bak '2i\
        Alias /static /website/static\
        <Directory /website/static>\
                Require all granted\
        </Directory>\
\
        <Directory /website/website>\
                <Files wsgi.py>\
                        Require all granted\
                </Files>\
        </Directory>\
\
        WSGIDaemonProcess website python-path=/website python-home=/website\
        WSGIProcessGroup website\
        WSGIScriptAlias / /website/website/wsgi.py\
' /etc/apache2/sites-available/000-default.conf

echo; echo -------- Installing Python and Pip --------; echo;
apt -y install python3 python3-pip libmysqlclient-dev # python, pip, libmysqlclient-dev is necessary to get the pip install of mysqlclient to work
pip3 install --upgrade pip
pip3 install mysqlclient

echo; echo -------- Installing MySQL --------; echo;
# setting up password entry setup, for when mysql is installed
echo "mysql-server mysql-server/root_password password woodensword" | debconf-set-selections
echo "mysql-server mysql-server/root_password_again password woodensword" | debconf-set-selections
apt -y install mysql-server
/etc/init.d/mysql start

echo; echo -------- Setting up a database and user in MySQL --------; echo;
# using 'expect', we interact with mysql to create a database and user for django to use
/usr/bin/expect << END
        spawn mysql -u root -p
        expect "Enter password: "
        send "woodensword\r"
        expect "mysql> "
        send "create database website;\r"
        expect "mysql> "
        send "create user 'app'@'localhost' identified by 'password';\r"
        expect "mysql> "
        send "grant all privileges on website.* to 'app'@'localhost';\r"
        expect "mysql> "
        send "exit\r"
END

echo; echo -------- Installing Django --------; echo;
pip3 install django

echo; echo -------- Setting up a Django project --------; echo;
django-admin startproject website
# add ip address to allowed hosts (attempts to find this automatically)
sed -i -e "s/ALLOWED_HOSTS = \[\]/ALLOWED_HOSTS = \['$(ifconfig eth0 2>/dev/null|awk '/inet addr:/ {print $2}'|sed 's/addr://')'\]/g" website/website/settings.py
# replace the Django database settings to use the mysql database set up earlier
sed -i -e  "/\
        'ENGINE': 'django.db.backends.sqlite3',/,/\
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),/\
{/'ENGINE': 'django.db.backends.sqlite3',/ s/.*/\
        'ENGINE': 'django.db.backends.mysql',\n\
        'NAME': 'website',\n\t'USER': 'app',\n\
        'PASSWORD': 'password',\n\
        'HOST': 'localhost',\n\
        'PORT': ''\
/; t; d}" website/website/settings.py
# static files directory setup
echo 'STATIC_ROOT = os.path.join(BASE_DIR, "static/")' >> website/website/settings.py
# run the makemigrations function in django (probably useless)
python3 website/manage.py makemigrations
# tell django to set itself up in the database
python3 website/manage.py migrate
# tell django to collect all of the static content into the directory location we configured
python3 website/manage.py collectstatic
# create the superuser 'root'
/usr/bin/expect << END
        spawn python3 website/manage.py createsuperuser
        expect "Username (leave blank to use 'root'): "
        send "\r"
        expect "Email address: "
        send "\r"
        expect "Password: "
        send "woodensword\r"
        expect "Password (again): "
        send "woodensword\r"
        expect "Superuser created successfully."
END

echo; echo -------- Setting Up Cron Updater --------; echo;
crontab -r
crontab << END
21 4 * * * /djangoProject/update >> /websiteUpdateLog
END
/etc/init.d/cron start

echo; echo -------- Loading Website Content --------; echo;
# perform load of website content code
# - coming soon -

# echo; echo -------- Starting Django Server --------; echo;
# python3 website/manage.py runserver 0.0.0.0:8080

echo; echo -------- Starting Apache Server --------; echo;
/etc/init.d/apache2 start