#!/bin/bash

if [ $# == 0 ]; then
	echo "error: loadCode requires a folder name"
	exit
fi

echo "- Loading files"
rm -r /website/*
cp -r /djangoProject/"$*"/* /website
echo ""

echo "- Attempting to make all migrations"
python3 /website/manage.py makemigrations
echo ""

echo "- Migrating"
python3 /website/manage.py migrate
echo ""

echo "- Collecting static files"
python3 /website/manage.py collectstatic
echo ""

echo "Done"
