#!/bin/bash

if [ $# == 0 ]; then
	echo "error: loadCode requires a folder name"
	exit
fi

rm -r /website/*
cp -r /djangoProject/"$*"/* /website
python3 /website/manage.py makemigrations
python3 /website/manage.py makemigrations newTwitter
python3 /website/manage.py migrate
