#!/bin/bash

if [ $# == 0 ]; then
        echo "error: loadCode requires a folder name"
        exit
fi

echo "- Cleaning out old data"
rm -r /djangoProject/"$*"/*
echo ""

echo "- Copying in new data"
cp -r /website/* /djangoProject/"$*"/
echo "(removing 'static' folder)"
rm -r /djangoProject/"$*"/static
echo ""

echo "Done"