#!/bin/bash

echo "Update Started : " $(date)
ans=$(git --git-dir /djangoProject/.git pull)
echo "-> " $ans
if [[ $ans == "Already up-to-date." ]]
then
        echo "No updates to be performed"
else
        echo "There's updates it seems"
        
        echo "Loading new content code into website directory"
        # - coming soon -

        echo "Restarting Apache"
        /etc/init.d/apache2 restart
fi

echo ""