# Generated by Django 2.0 on 2017-12-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conVerse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verse',
            name='text',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
