# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conVerse', '0002_auto_20171219_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verse',
            name='text',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
