# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuousVerse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verse',
            name='id',
        ),
        migrations.AddField(
            model_name='verse',
            name='verseId',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
