# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuousVerse', '0002_auto_20171029_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verse',
            name='verseId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
